/*
 * 由SharpDevelop创建。
 * 用户： EmingK
 * 日期: 2013/8/22
 * 时间: 15:24
 * 
 * 要改变这种模板请点击 工具|选项|代码编写|编辑标准头文件
 */
using System;
using System.IO;

namespace osm
{
	/// <summary>
	/// Description of Class1.
	/// </summary>
	public class osmProcessor
	{
		private StreamReader osmReader;
		
		public osmProcessor()
		{
		}
		
		public osmProcessor(string filename)
		{
			osmReader=new StreamReader(filename);
		}
		
		public void setFile(string filename)
		{
			osmReader=new StreamReader(filename);
		}
		
		public void writeOutput()
		{
			string currentRead;
			// write before begin
			while(!osmReader.EndOfStream)
			{
				currentRead=osmReader.ReadLine();
				if(currentRead.Trim().StartsWith("#begin"))
				{
					goto modstart;
				}
				Console.WriteLine(currentRead);
			}
			return;
			// write legend
		modstart:
			writeLegend();
			// write mod header
			Console.WriteLine("[notice]");
			// write mod
			while(!osmReader.EndOfStream)
			{
				currentRead=osmReader.ReadLine();
				if(currentRead.Trim().StartsWith("#end"))
				{
					goto modend;
				}
				else
				{
					if(currentRead.StartsWith("!"))
					{
					   	// unrankable
					   	Console.Write("[color=#ff0000]");
					   	Console.Write(currentRead.Substring(1).Trim());
					   	Console.WriteLine("[/color]");
					}
					else if(currentRead.StartsWith("*"))
					{
						// should fix
						Console.Write("[color=#8000FF]");
					   	Console.Write(currentRead.Substring(1).Trim());
					   	Console.WriteLine("[/color]");
					}
					else if(currentRead.StartsWith("-"))
					{
						Console.Write("[color=#000000]");
					   	Console.Write(currentRead.Substring(1).Trim());
					   	Console.WriteLine("[/color]");
					}
					else if(currentRead.StartsWith("."))
					{
						Console.Write("[color=#808080]");
					   	Console.Write(currentRead.Substring(1).Trim());
					   	Console.WriteLine("[/color]");
					}
					else
					{
						Console.WriteLine(currentRead);
					}
				}
			}
			Console.WriteLine("[/notice]");
			return;
			// write mod tail
		modend:
			Console.WriteLine("[/notice]");
			// write after end
			while(!osmReader.EndOfStream)
			{
				currentRead=osmReader.ReadLine();
				Console.WriteLine(currentRead);
			}
		}
		
		private void writeLegend()
		{
			Console.Write(
@"[color=#808080]This post is generated by EK's osu modpost generator.[/color]
[notice][color=#FF0000]Red=unrankable issue[/color]
[color=#8000FF]Purple=Emphasis suggestion[/color]
[color=#000000]Black=Suggestion[/color]
[color=#808080]Gray=Feel free to ignore[/color][/notice]");
			Console.WriteLine();
		}
	}
}
